---
title: "Markdown_report"
author: "Luuk Torn"
date: "2025-04-09"
output: html_document
bibliography: bibliography.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary Report group F4

## Influences of weather on vegetation phenology of 6 habitat types in the Hoge Veluwe

#### Introduction

Camera traps have long been used to give information on the behavior and ecology of animals. Nowadays, due to the emergence of algorithms used for image analysis, analyzing camera trap data has become much faster and more predictive. Camera traps are not only useful for gathering data about animals, but also about vegetation. Information from these so-called phenocams can be used to get insight into changes in vegetation over a period of time, known as phenology. For instance, images can provide information about the phenophase of the vegetation: the onset of blooming of certain flowers, the emergence of the first green leaves during spring, or the start of the coloring of leaves in autumn. These phenology metrics can then be explained and even predicted by searching for correlations with abiotic factors, such as weather patterns. 

In this project, we aim to find predictors in weather data (such as humidity and sunlight) to explain patterns in phenology metrics across six different habitat types in the Hoge Veluwe. We will be using the data from 56-70 camera's which have been taking photo's every day at noon for multiple years. To achieve this, the following steps will be taken: 

1.  Determining the vegetation region of interest (ROI) inside the images
2.  Filtering out deviating images based on criteria
3.  Curve fitting on change in green chromatic coordinates (Gcc) over time
4.  Classify the vegetation in the images into phenophase groups based on change in Gcc
5.  Calculate metrics that summarize phenophases per time period
6.  Calculating variables out of weather data that are of interest
7.  Analyze the correlation between weather parameters and the change in phenophase metrics over time

#### 1. Determining ROI

Images from the same site contain depictions of multiple vegetation types. To facilitate later analysis, a region of interest (ROI) must be drawn around the area in the images of one site in which a specific vegetation type is present. For instance, in the oak scrubland, the focus could be on the oak canopy, but also on the shrubs or grasses on the ground. The Phenopix package [@filippa2016] provides a function to draw the ROI. We first focus on the canopy of oak forests. In code below, there is an option to draw the ROI yourself, or use a pre-drawn ROI.

#### 2. Filtering out deviating images. 
The habitat we have decided to analyse further regarding influences of weather on vegetation phenology is habitat 5, Oak scrublands and forest cultures. We´re focusing on site 1 which is unrestricted. In general an unrestricted site refers to a specific area that does not have restrictions regarding access, usage or activities. The data consists of 2405 images taken at noon every day from 2013/07/10 to 2020/03/25. To do the times series analysis the deviating images need to be filtered out. Issues like bad weather conditions, low illumination and dirty lenses create noise in the data set. We decided due to simplicity to filter out the deviating images manually. 




